services:
  resume:
    image: imprevisible/resume
    container_name: resume
    ports:
      - "8080:80"
    environment:
      - PASSCODE=your_passcode_to_add_and_delete_resume
    volumes:
      - /DATA/AppData/resume:/usr/share/nginx/html/assets/resume
